name: ombudsman
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen:
  google_fonts: ^0.1.1
  flutter_datetime_picker: ^1.3.2
  fa_stepper: ^0.0.2
  grouped_checkbox: ^1.0.0
  flutter_svg: ^0.18.0
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.0.3
  intl: ^0.16.1
  shared_preferences: ^0.5.7
  link: ^1.1.0
  advance_pdf_viewer: ^1.2.0
  image_picker: ^0.6.7
  readmore: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.8.1
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icons/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - icons/logo.png
    - icons/profil.png
    - icons/monitor.png
    - icons/paper.png
    - icons/speaker.png
    - icons/star.png
    - icons/strategy.png

    - images/logo.png
    - images/logo_ori.png
    - images/prosedur.svg
    - images/avatar.png

    - images/laporan.svg

    - images/profil/profil_singkat.svg
    - images/profil/tugas_fungsi.svg
    - images/profil/struktur.png
    - images/profil/visi_misi.svg
    - images/profil/motto.svg
    - images/standar_layanan/standar.svg
    - images/standar_layanan/maklumat.svg

    - file/7_UU_file_20171129_213852.PDF
    - file/6_UU_file_20171129_213537.pdf
    - file/19_PP_file_20171129_215638.pdf
    - file/327_KK_file_20200729_090043.pdf
    - file/61_PPIK_file_20180116_090046.pdf

    - file/SERTAMERTA.pdf
    - file/SETIAPSAAT.pdf
    - file/SECARABERKALA.pdf

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
